import { useLangContext } from '@/components/hooks/LangContext'
import LabelSectionDark from '@/components/material/LabelSectionDark'
import Image from 'next/image'
import React from 'react'

export default function OurTeams() {
      const { lang } = useLangContext()
      return (
            <>
                  <main className='w-full h-auto overflow-hidden relative z-[2] text-slate-800 lg:pb-[250px] pb-[200px]'>
                        <section className='container_section flex flex-col items-start justify-start'>
                              {/* Text */}
                              <div className='w-full flex flex-col'>
                                    <LabelSectionDark title={lang === 'ID' ? 'Tim Kami' : 'Our Teams'} />
                                    <h2 className='w-full md:max-w-[500px] max-w-none font-normal lg:text-[48px] text-[24px] leading-tight lg:mt-[14px] mt-2 lg:mb-[50px] mb-6'>
                                          <span className='font-bold'>
                                                {lang === 'ID' ? 'Tangan Terpercaya' : 'Trusted Hands'}
                                          </span>{' '}
                                          <span className='font-bold text-slate-700'>
                                                {lang === 'ID' ? 'di Balik' : 'Behind'}
                                          </span>{' '}
                                          <span className='font-bold text-theme-red'>
                                                {lang === 'ID' ? 'Setiap Penerbangan' : 'Every Flight'}
                                          </span>
                                    </h2>
                              </div>

                              {/* Teams */}
                              <div className='w-full flex flex-col lg:gap-6 gap-5'>
                                    <div className='w-full flex lg:flex-row flex-col items-center gap-2'>
                                          {/* PROFILE */}
                                          <div className='lg:w-[450px] h-[450px] w-full bg-transparent flex-shrink-0 overflow-hidden'>
                                                <Image src={'/assets/images/teams1.svg'} alt='teams' width={300} height={400} className='w-full h-full object-contain' />
                                          </div>
                                          {/* DESC */}
                                          <p className='block w-full font-medium lg:text-base text-sm text-slate-800 leading-normal flex-grow-0'>
                                                {lang === 'ID' ? ' Pengusaha berpengalaman dengan lebih dari satu dekade di industri penerbangan Indonesia, Mohamad Nazars telah membangun reputasi atas inovasi strategis dan keunggulan operasional. Kariernya dimulai dengan pendirian PT Aero Teknologi Internasional, perusahaan teknologi penerbangan yang menjadi perwakilan resmi AEROPROC LLC (AS). Di bawah kepemimpinannya, perusahaan tersebut sukses memperkenalkan dan memasarkan solusi penerbangan kelas dunia—termasuk AT-802 FuelBoss, helikopter Kaman K-Max, dan peralatan khusus dari SEI Industries ke pasar Indonesia. Ia juga dikenal atas kontribusinya membantu pemerintah Indonesia membangun sistem pengangkutan bahan bakar terbang paling efisien ke daerah terpencil di Papua menggunakan pesawat AT-802 FuelBoss, sehingga menurunkan harga bahan bakar di wilayah tersebut. Saat ini, di PT Asia Aero Technology, ia mempelopori pengembangan unit bisnis strategis rantai pasok suku cadang pesawat udara—inisiatif berani yang memberikan dukungan krusial bagi MRO nasional, maskapai komersial, dan sektor penerbangan militer. Pekerjaanya mencerminkan komitmen untuk meningkatkan infrastruktur penerbangan Indonesia dengan memadukan wawasan teknis dan kepemimpinan pragmatis. Visi Mohamad Nazars adalah mentransformasi PT Asia Aero Technology menjadi pusat penerbangan regional yang unggul, memberdayakan stakeholder industry penerbangan dengan layanan andal, kemitraan global, dan solusi rantai pasok yang berpandangan ke depan.' : 'A seasoned entrepreneur with over a decade of experience in Indonesia’s aviation industry, Mohamad Nazars has established a reputation for strategic innovation and operational excellence. His career began with the founding of PT Aero Teknologi Internasional, an aviation technology company that served as the official representative of AEROPROC LLC (USA). Under his leadership, the firm successfully introduced and promoted globally recognized aviation solutions, including the AT-802 FuelBoss, Kaman K-Max Helicopter, and SEI Industries’ specialized equipment, to the Indonesian market. He is acknowledged for helping Indonesian government for establishing the most efficient flying fuel hauling system to the remotest area of Papua region using AT 802 FuelBoss Aircraft, enabling cheaper fuel price in the region. Currently, at PT Asia Aero Technology, he is spearheading the development of a strategic aircraft spare part supply chain business unit. a bold initiative that provides critical support to national MROs, commercial airlines, and military aviation sectors. His work reflects a commitment to elevating Indonesia’s aviation infrastructure, blending technical insight with pragmatic leadership. Mohamad Nazar vision is to transform PT Asia Aero Technology into a regional hub for aviation excellence, empowering industry stakeholders with reliable service, global partnerships, and forward-thinking supply solutions.'}
                                          </p>
                                    </div>
                                    <div className='w-full flex lg:flex-row flex-col items-center gap-2'>
                                          {/* DESC */}
                                          <p className='block w-full font-medium lg:text-base text-sm text-slate-800 leading-normal flex-grow-0 lg:text-end text-start lg:order-1 order-2'>
                                                {lang === 'ID' ? ' Pengusaha berpengalaman dengan lebih dari satu dekade di industri penerbangan Indonesia, Mohamad Nazars telah membangun reputasi atas inovasi strategis dan keunggulan operasional. Kariernya dimulai dengan pendirian PT Aero Teknologi Internasional, perusahaan teknologi penerbangan yang menjadi perwakilan resmi AEROPROC LLC (AS). Di bawah kepemimpinannya, perusahaan tersebut sukses memperkenalkan dan memasarkan solusi penerbangan kelas dunia—termasuk AT-802 FuelBoss, helikopter Kaman K-Max, dan peralatan khusus dari SEI Industries ke pasar Indonesia. Ia juga dikenal atas kontribusinya membantu pemerintah Indonesia membangun sistem pengangkutan bahan bakar terbang paling efisien ke daerah terpencil di Papua menggunakan pesawat AT-802 FuelBoss, sehingga menurunkan harga bahan bakar di wilayah tersebut. Saat ini, di PT Asia Aero Technology, ia mempelopori pengembangan unit bisnis strategis rantai pasok suku cadang pesawat udara—inisiatif berani yang memberikan dukungan krusial bagi MRO nasional, maskapai komersial, dan sektor penerbangan militer. Pekerjaanya mencerminkan komitmen untuk meningkatkan infrastruktur penerbangan Indonesia dengan memadukan wawasan teknis dan kepemimpinan pragmatis. Visi Mohamad Nazars adalah mentransformasi PT Asia Aero Technology menjadi pusat penerbangan regional yang unggul, memberdayakan stakeholder industry penerbangan dengan layanan andal, kemitraan global, dan solusi rantai pasok yang berpandangan ke depan.' : 'A seasoned entrepreneur with over a decade of experience in Indonesia’s aviation industry, Mohamad Nazars has established a reputation for strategic innovation and operational excellence. His career began with the founding of PT Aero Teknologi Internasional, an aviation technology company that served as the official representative of AEROPROC LLC (USA). Under his leadership, the firm successfully introduced and promoted globally recognized aviation solutions, including the AT-802 FuelBoss, Kaman K-Max Helicopter, and SEI Industries’ specialized equipment, to the Indonesian market. He is acknowledged for helping Indonesian government for establishing the most efficient flying fuel hauling system to the remotest area of Papua region using AT 802 FuelBoss Aircraft, enabling cheaper fuel price in the region. Currently, at PT Asia Aero Technology, he is spearheading the development of a strategic aircraft spare part supply chain business unit. a bold initiative that provides critical support to national MROs, commercial airlines, and military aviation sectors. His work reflects a commitment to elevating Indonesia’s aviation infrastructure, blending technical insight with pragmatic leadership. Mohamad Nazar vision is to transform PT Asia Aero Technology into a regional hub for aviation excellence, empowering industry stakeholders with reliable service, global partnerships, and forward-thinking supply solutions.'}
                                          </p>
                                          {/* PROFILE */}
                                          <div className='lg:w-[450px] h-[450px] w-full bg-transparent flex-shrink-0 overflow-hidden lg:order-2 order-1'>
                                                <Image src={'/assets/images/teams2.svg'} alt='teams' width={300} height={400} className='w-full h-full object-contain' />
                                          </div>
                                    </div>
                                    <div className='w-full flex lg:flex-row flex-col items-center gap-2'>
                                          {/* PROFILE */}
                                          <div className='lg:w-[450px] h-[450px] w-full bg-transparent flex-shrink-0 overflow-hidden'>
                                                <Image src={'/assets/images/teams1.svg'} alt='teams' width={300} height={400} className='w-full h-full object-contain' />
                                          </div>
                                          {/* DESC */}
                                          <p className='block w-full font-medium lg:text-base text-sm text-slate-800 leading-normal flex-grow-0'>
                                                {lang === 'ID' ? ' Pengusaha berpengalaman dengan lebih dari satu dekade di industri penerbangan Indonesia, Mohamad Nazars telah membangun reputasi atas inovasi strategis dan keunggulan operasional. Kariernya dimulai dengan pendirian PT Aero Teknologi Internasional, perusahaan teknologi penerbangan yang menjadi perwakilan resmi AEROPROC LLC (AS). Di bawah kepemimpinannya, perusahaan tersebut sukses memperkenalkan dan memasarkan solusi penerbangan kelas dunia—termasuk AT-802 FuelBoss, helikopter Kaman K-Max, dan peralatan khusus dari SEI Industries ke pasar Indonesia. Ia juga dikenal atas kontribusinya membantu pemerintah Indonesia membangun sistem pengangkutan bahan bakar terbang paling efisien ke daerah terpencil di Papua menggunakan pesawat AT-802 FuelBoss, sehingga menurunkan harga bahan bakar di wilayah tersebut. Saat ini, di PT Asia Aero Technology, ia mempelopori pengembangan unit bisnis strategis rantai pasok suku cadang pesawat udara—inisiatif berani yang memberikan dukungan krusial bagi MRO nasional, maskapai komersial, dan sektor penerbangan militer. Pekerjaanya mencerminkan komitmen untuk meningkatkan infrastruktur penerbangan Indonesia dengan memadukan wawasan teknis dan kepemimpinan pragmatis. Visi Mohamad Nazars adalah mentransformasi PT Asia Aero Technology menjadi pusat penerbangan regional yang unggul, memberdayakan stakeholder industry penerbangan dengan layanan andal, kemitraan global, dan solusi rantai pasok yang berpandangan ke depan.' : 'A seasoned entrepreneur with over a decade of experience in Indonesia’s aviation industry, Mohamad Nazars has established a reputation for strategic innovation and operational excellence. His career began with the founding of PT Aero Teknologi Internasional, an aviation technology company that served as the official representative of AEROPROC LLC (USA). Under his leadership, the firm successfully introduced and promoted globally recognized aviation solutions, including the AT-802 FuelBoss, Kaman K-Max Helicopter, and SEI Industries’ specialized equipment, to the Indonesian market. He is acknowledged for helping Indonesian government for establishing the most efficient flying fuel hauling system to the remotest area of Papua region using AT 802 FuelBoss Aircraft, enabling cheaper fuel price in the region. Currently, at PT Asia Aero Technology, he is spearheading the development of a strategic aircraft spare part supply chain business unit. a bold initiative that provides critical support to national MROs, commercial airlines, and military aviation sectors. His work reflects a commitment to elevating Indonesia’s aviation infrastructure, blending technical insight with pragmatic leadership. Mohamad Nazar vision is to transform PT Asia Aero Technology into a regional hub for aviation excellence, empowering industry stakeholders with reliable service, global partnerships, and forward-thinking supply solutions.'}
                                          </p>
                                    </div>
                                    <div className='w-full flex lg:flex-row flex-col items-center gap-2'>
                                          {/* DESC */}
                                          <p className='block w-full font-medium lg:text-base text-sm text-slate-800 leading-normal flex-grow-0 lg:text-end text-start lg:order-1 order-2'>
                                                {lang === 'ID' ? ' Pengusaha berpengalaman dengan lebih dari satu dekade di industri penerbangan Indonesia, Mohamad Nazars telah membangun reputasi atas inovasi strategis dan keunggulan operasional. Kariernya dimulai dengan pendirian PT Aero Teknologi Internasional, perusahaan teknologi penerbangan yang menjadi perwakilan resmi AEROPROC LLC (AS). Di bawah kepemimpinannya, perusahaan tersebut sukses memperkenalkan dan memasarkan solusi penerbangan kelas dunia—termasuk AT-802 FuelBoss, helikopter Kaman K-Max, dan peralatan khusus dari SEI Industries ke pasar Indonesia. Ia juga dikenal atas kontribusinya membantu pemerintah Indonesia membangun sistem pengangkutan bahan bakar terbang paling efisien ke daerah terpencil di Papua menggunakan pesawat AT-802 FuelBoss, sehingga menurunkan harga bahan bakar di wilayah tersebut. Saat ini, di PT Asia Aero Technology, ia mempelopori pengembangan unit bisnis strategis rantai pasok suku cadang pesawat udara—inisiatif berani yang memberikan dukungan krusial bagi MRO nasional, maskapai komersial, dan sektor penerbangan militer. Pekerjaanya mencerminkan komitmen untuk meningkatkan infrastruktur penerbangan Indonesia dengan memadukan wawasan teknis dan kepemimpinan pragmatis. Visi Mohamad Nazars adalah mentransformasi PT Asia Aero Technology menjadi pusat penerbangan regional yang unggul, memberdayakan stakeholder industry penerbangan dengan layanan andal, kemitraan global, dan solusi rantai pasok yang berpandangan ke depan.' : 'A seasoned entrepreneur with over a decade of experience in Indonesia’s aviation industry, Mohamad Nazars has established a reputation for strategic innovation and operational excellence. His career began with the founding of PT Aero Teknologi Internasional, an aviation technology company that served as the official representative of AEROPROC LLC (USA). Under his leadership, the firm successfully introduced and promoted globally recognized aviation solutions, including the AT-802 FuelBoss, Kaman K-Max Helicopter, and SEI Industries’ specialized equipment, to the Indonesian market. He is acknowledged for helping Indonesian government for establishing the most efficient flying fuel hauling system to the remotest area of Papua region using AT 802 FuelBoss Aircraft, enabling cheaper fuel price in the region. Currently, at PT Asia Aero Technology, he is spearheading the development of a strategic aircraft spare part supply chain business unit. a bold initiative that provides critical support to national MROs, commercial airlines, and military aviation sectors. His work reflects a commitment to elevating Indonesia’s aviation infrastructure, blending technical insight with pragmatic leadership. Mohamad Nazar vision is to transform PT Asia Aero Technology into a regional hub for aviation excellence, empowering industry stakeholders with reliable service, global partnerships, and forward-thinking supply solutions.'}
                                          </p>
                                          {/* PROFILE */}
                                          <div className='lg:w-[450px] h-[450px] w-full bg-transparent flex-shrink-0 overflow-hidden lg:order-2 order-1'>
                                                <Image src={'/assets/images/teams2.svg'} alt='teams' width={300} height={400} className='w-full h-full object-contain' />
                                          </div>
                                    </div>
                              </div>
                        </section>
                  </main>
            </>
      )
}
